-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 12:41:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Prefeitura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Prefeitura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prefeitura` DEFAULT CHARACTER SET utf8 ;
USE `Prefeitura` ;

-- -----------------------------------------------------
-- Table `Prefeitura`.`Favorecido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prefeitura`.`Favorecido` (
  `IdFavorecido` INT NOT NULL AUTO_INCREMENT,
  `CPF_CNPJ` CHAR(14) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdFavorecido`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC),
  UNIQUE INDEX `IdFavorecido_UNIQUE` (`IdFavorecido` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prefeitura`.`Empenho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prefeitura`.`Empenho` (
  `Especie` VARCHAR(25) NOT NULL,
  `Orgao` VARCHAR(100) NOT NULL,
  `Projeto` VARCHAR(100) NOT NULL,
  `Elemento` VARCHAR(100) NOT NULL,
  `Licitacao` VARCHAR(50) NOT NULL,
  `Processo` VARCHAR(30) NOT NULL,
  `DataEmpenho` DATE NOT NULL,
  `Valor` FLOAT NOT NULL,
  `Empenho_Numero` INT NOT NULL,
  `IdFavorecido` INT NOT NULL,
  `Funcao` VARCHAR(100) NOT NULL,
  `SubFuncao` VARCHAR(100) NOT NULL,
  `Programa` VARCHAR(100) NOT NULL,
  `Destinacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Empenho_Numero`, `IdFavorecido`),
  INDEX `fk_Empenho_Favorecido1_idx` (`IdFavorecido` ASC),
  CONSTRAINT `fk_Empenho_Favorecido1`
    FOREIGN KEY (`IdFavorecido`)
    REFERENCES `Prefeitura`.`Favorecido` (`IdFavorecido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prefeitura`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prefeitura`.`Pagamento` (
  `Numero` INT NOT NULL,
  `DataPagamento` DATE NOT NULL,
  `ValorPagamento` FLOAT NOT NULL,
  `Empenho_Numero` INT NOT NULL,
  PRIMARY KEY (`Numero`, `Empenho_Numero`),
  INDEX `fk_Pagamento_Empenho1_idx` (`Empenho_Numero` ASC),
  CONSTRAINT `fk_Pagamento_Empenho1`
    FOREIGN KEY (`Empenho_Numero`)
    REFERENCES `Prefeitura`.`Empenho` (`Empenho_Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
