# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0017_auto_20180827_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.Orgao', verbose_name='Orgão'),
        ),
    ]
