# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre a cidade'),
        ),
    ]
