# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0006_orgao_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
