# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0007_auto_20180820_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.Orgao', verbose_name='Orgao'),
        ),
    ]
