# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0012_auto_20180820_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProjeto', models.TextField(max_length=100, verbose_name='Projeto')),
                ('slug', models.SlugField(verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.Orgao', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nameProjeto'],
            },
        ),
    ]
