# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0014_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
