# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-27 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0015_projeto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='orgao',
        ),
        migrations.AddField(
            model_name='projeto',
            name='Orgao',
            field=models.TextField(default='maravilhas', max_length=100, verbose_name='Orgão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projeto',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cidades.Cidade', verbose_name='Cidade'),
            preserve_default=False,
        ),
    ]
