# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-27 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0016_auto_20180827_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='Orgao',
            new_name='orgao',
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nameOrgao',
            field=models.TextField(max_length=100, unique=True, verbose_name='Orgao'),
        ),
    ]
