# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-06 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0018_auto_20180827_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='orgao',
        ),
        migrations.DeleteModel(
            name='Orgao',
        ),
    ]
