# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0019_auto_20180906_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre a cidade'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
