# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0021_auto_20180908_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
    ]
