# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0022_auto_20180908_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nameCidade',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Identificador'),
        ),
    ]
