# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0023_auto_20180908_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='slug',
            field=models.SlugField(verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(verbose_name='Identificador'),
        ),
    ]
