# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0025_auto_20180908_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nameProjeto',
            field=models.TextField(max_length=100, unique=True, verbose_name='Projeto'),
        ),
    ]
