# Generated by Django 2.1.1 on 2018-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0027_auto_20180909_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='idcliente',
            field=models.IntegerField(default='1', verbose_name='idcliente'),
            preserve_default=False,
        ),
    ]
