# Generated by Django 2.1.1 on 2018-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0028_cidade_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='idcliente',
            field=models.CharField(max_length=100, verbose_name='idcliente'),
        ),
    ]
