# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0029_auto_20180909_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='idcliente',
        ),
        migrations.AddField(
            model_name='cidade',
            name='idCliente',
            field=models.IntegerField(default=255, verbose_name='idCliente'),
            preserve_default=False,
        ),
    ]
