# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0030_auto_20180910_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.IntegerField(verbose_name='empID')),
                ('empOrgao', models.CharField(blank=True, max_length=100, verbose_name='empOrgao')),
                ('empData', models.CharField(blank=True, max_length=100, verbose_name='empData')),
                ('empValor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='empIdFav')),
                ('empIdFav', models.CharField(blank=True, max_length=100)),
                ('empFuncao', models.CharField(blank=True, max_length=100, verbose_name='empFuncao')),
                ('empSubFuncao', models.CharField(blank=True, max_length=100, verbose_name='empSubFuncao')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.Cidade', verbose_name='empIdCliente')),
            ],
        ),
    ]
