# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0031_empenho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='empIdFav',
            field=models.CharField(blank=True, max_length=100, verbose_name='empIdFav'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empValor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, verbose_name='empValor'),
        ),
    ]
