# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0032_auto_20180910_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empenho',
            old_name='idCliente',
            new_name='empIdCliente',
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empSubFuncao',
            field=models.CharField(blank=True, max_length=200, verbose_name='empSubFuncao'),
        ),
    ]
