# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0033_auto_20180910_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenho',
            name='empIdCliente',
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empData',
            field=models.CharField(max_length=100, verbose_name='empData'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empFuncao',
            field=models.CharField(max_length=200, verbose_name='empFuncao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empIdFav',
            field=models.CharField(max_length=100, verbose_name='empIdFav'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empOrgao',
            field=models.CharField(max_length=100, verbose_name='empOrgao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empSubFuncao',
            field=models.CharField(max_length=200, verbose_name='empSubFuncao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empValor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='empValor'),
        ),
    ]
