# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0035_empenho_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='empID',
            field=models.IntegerField(null=True, verbose_name='empID'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empSubFuncao',
            field=models.CharField(max_length=200, null=True, verbose_name='empSubFuncao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='idCliente',
            field=models.IntegerField(verbose_name='idCliente'),
        ),
    ]
