# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0036_auto_20180910_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='empData',
            field=models.CharField(max_length=100, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empFuncao',
            field=models.CharField(max_length=200, verbose_name='Funcao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empID',
            field=models.IntegerField(null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empIdFav',
            field=models.CharField(max_length=100, verbose_name='IdFav'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empOrgao',
            field=models.CharField(max_length=100, verbose_name='Orgao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='empSubFuncao',
            field=models.CharField(max_length=200, null=True, verbose_name='SubFuncao'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='idCliente',
            field=models.IntegerField(verbose_name='Cliente'),
        ),
    ]
