# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-10 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0037_auto_20180910_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='empValor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
    ]
